# Generated by Django 5.2.1 on 2025-05-20 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MeetFlowV1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='LocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_options', to='MeetFlowV1.event')),
            ],
            options={
                'verbose_name': 'Location Option',
                'verbose_name_plural': 'Location Options',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invitation', 'Event Invitation'), ('reminder', 'Event Reminder'), ('update', 'Event Update'), ('confirmation', 'Event Confirmation'), ('cancellation', 'Event Cancellation')], max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MeetFlowV1.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_options', to='MeetFlowV1.event')),
            ],
            options={
                'verbose_name': 'Time Option',
                'verbose_name_plural': 'Time Options',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='pending', max_length=20)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='MeetFlowV1.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-sent_date'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LocationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0, help_text='From 0 to 5, where 5 is the highest preference')),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('location_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='MeetFlowV1.locationoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Vote',
                'verbose_name_plural': 'Location Votes',
                'unique_together': {('user', 'location_option')},
            },
        ),
        migrations.CreateModel(
            name='TimeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0, help_text='From 0 to 5, where 5 is the highest preference')),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('time_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='MeetFlowV1.timeoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Vote',
                'verbose_name_plural': 'Time Votes',
                'unique_together': {('user', 'time_option')},
            },
        ),
    ]
