# Generated by Django 5.2.1 on 2026-05-04 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetFlowV1', '0003_course_unit_exercise_adaptivequeue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='userexerciseattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='module',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='module',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='MeetFlowV1.module'),
        ),
        migrations.CreateModel(
            name='AIExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BLANKS', 'Fill in the blanks'), ('PARSONS', 'Parsons Problems'), ('DEBUG', 'Debugging'), ('CODE', 'Coding Task')], max_length=20)),
                ('content', models.JSONField(help_text='Exercise content/structure')),
                ('solution', models.JSONField(help_text='Expected solution')),
                ('ai_metadata', models.JSONField(blank=True, help_text='AI generation metadata', null=True)),
                ('source_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_exercises', to='MeetFlowV1.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userexerciseattempt',
            name='ai_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MeetFlowV1.aiexercise'),
        ),
        migrations.CreateModel(
            name='MasterExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BLANKS', 'Fill in the blanks'), ('PARSONS', 'Parsons Problems'), ('DEBUG', 'Debugging'), ('CODE', 'Coding Task')], max_length=20)),
                ('content', models.JSONField(help_text='Exercise content/structure')),
                ('solution', models.JSONField(help_text='Expected solution')),
                ('ai_metadata', models.JSONField(blank=True, help_text='AI generation metadata', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_exercises', to='MeetFlowV1.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userexerciseattempt',
            name='master_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MeetFlowV1.masterexercise'),
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='MeetFlowV1.module')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='MeetFlowV1.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dependencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('source_node', 'target_node', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='AdaptiveQueue',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.RemoveField(
            model_name='userexerciseattempt',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
