# Generated by Django 5.2.1 on 2026-05-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetFlowV1', '0004_remove_unit_course_remove_exercise_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='reinforcement_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='source_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reinforcements', to='MeetFlowV1.module'),
        ),
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('COMPLETED', 'Completed'), ('STUCK', 'Stuck')], default='LOCKED', max_length=20),
        ),
    ]
