# Generated by Django 5.2.1 on 2026-05-06 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetFlowV1', '0005_module_reinforcement_type_module_source_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexerciseattempt',
            name='ai_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='MeetFlowV1.aiexercise'),
        ),
        migrations.AlterField(
            model_name='userexerciseattempt',
            name='master_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='MeetFlowV1.masterexercise'),
        ),
        migrations.AlterUniqueTogether(
            name='userexerciseattempt',
            unique_together={('user', 'ai_exercise'), ('user', 'master_exercise')},
        ),
    ]
